# Generated by Django 5.0.4 on 2024-04-27 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_rename_source_website_product_website'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='website',
            field=models.CharField(max_length=1000),
        ),
    ]
